baseURL = "https://h-michael.com"
languageCode = "ja-jp"
title = "因果応報"
theme = "Hugo-Octopress"
disqusShortname = "h-michael"
hasCJKLanguage = true
enableemoji = true
paginate = 10
paginatePath = "page"
pygmentscodefences = true

[permalinks]
    post = "/:year/:month/:day/:filename/"
    code = "/:filename/"

[taxonomies]
    tag = "tags"
    category = "categories"

[author]
    name = "Hirokazu Hata"
    email = "h[dot]hata[dot]ai[dot]t[at]gmail.com"

[params]

  # If false, all contents of posts will appear on the front page and in pagination
  truncate = true

  # Author's name (appears in meta tags and under posts)
  author = "Hirokazu Hata"

  # This text appears in site header under website title
  subtitle = "忘れないうちに書き留める"

  BrandImage = "/images/me.png"

  # Search engine URL
  searchEngineURL = "https://www.google.com/search"

  # Text of the "Continue Reading" label. Supports markdown and inline HTML.
  # For example, &rarr; == right arrow.
  continueReadingText = "Would you like to know more? &rarr;"

  # Google analytics code - remove if you do not have/want Google Analytics - needs JavaScript
  googleAnalytics = "UA-44654685-3"

  # Switch to true to enable RSS icon link
  rss = true

  # Set to true to use a text label for RSS instead of an icon
  # This is overwritten by the "rss" setting
  textrss = false

  # Website's default description
  defaultDescription = "programming"

  # Populate with your search keywords - these will appear in meta tags
  # defaultKeywords = ["keyword1" , "keyword2" , "keyword3" , "keyword4"]

  # Set to true to hide ReadingTime on posts
  disableReadingTime = false

  # Set to true to disable downloading of remote Google fonts
  disableGoogleFonts = false

  # Remove or set to false to use local fonts
  remoteFonts = false

  # Remove or set to false to use FontAwesome CDN, otherwise, the theme uses ForkAwesome local fonts.
  # fontAwesome = false

  # If set to true, navigation menu links will open in a new window with the exception of links to root ("/")
  # If this item does not exist or is set to false, then navigation menu links will open in the same window
  showRightSidebar = true
  navigationNewWindow = false
  sidebarRecentLimit = 5
  generateTaxonomyList = true
  # sidebarHeader = "This blog"
  sidebarMenuEnabled = true
  sidebarMenuHeader = "Reccomend Categories"
  notFoundHeader = "404"
  notFoundText = "404"

  twitter  = "https://twitter.com/h_michael_z"
  linkedin = "https://www.linkedin.com/in/hirokazu-hata-18778a84/"
  github   = "https://github.com/h-michael"

[[menu.main]]
  Name = "Home"
  URL = "/"
  weight = -200

[[menu.main]]
  name = "Categories"
  url = "/categories/"
  weight = -100

[[menu.main]]
  name = "Archives"
  url = "/post/"
  weight = -50

[[menu.sidebar]]
  name = "Rust"
  url = "/categories/rust/"
